version: 2.1

orbs:
  python: circleci/python@1.4.0

workflows:
  cea-ci:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.5
      - image: postgres:12.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: currency_exchange_app
          POSTGRES_PASSWORD: password

    steps:
      - checkout
      - python/install-packages:
          args: 'pytest pytest-cov pytest-django'
          pkg-manager: pipenv
      - run:
          command: |
            pipenv run python manage.py collectstatic --no-input
            pipenv run pytest
