# Generated by Django 3.2.2 on 2021-05-10 10:54
import djmoney.models.fields
import djmoney.models.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_auto_20210510_0947"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="txn_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=4,
                max_digits=19,
                null=True,
                validators=[djmoney.models.validators.MinMoneyValidator(1)],
                verbose_name="Amount",
            ),
        ),
    ]
