# Generated by Django 3.2.2 on 2021-05-10 11:12
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_transaction_txn_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
