# Generated by Django 3.2.2 on 2021-05-10 11:16
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_transaction_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-created"]},
        ),
    ]
