# Generated by Django 3.2.2 on 2021-05-09 09:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
