# Generated by Django 3.2.2 on 2021-05-10 07:00
from django.conf import settings
from django.db import migrations
from django.db import models

import wallet.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallet", "0004_alter_wallet_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.ForeignKey(
                on_delete=models.SET(wallet.models.get_sentinel_user),
                related_name="wallets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
