# Generated by Django 3.2.2 on 2021-05-10 07:08
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0005_alter_wallet_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="name",
            field=models.CharField(default="Default Set", max_length=25),
            preserve_default=False,
        ),
    ]
