# Generated by Django 3.2.2 on 2021-05-12 04:42
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0009_auto_20210510_1112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="profile_pic",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile_pic"
            ),
        ),
    ]
